services:
  python_container:
    image: python_image
    container_name: python_container
    command: bash -c "service mysql start && sleep 5 && mysql -u user1 -p'password@123' < /src/initialdata.sql && crontab /src/cron-schedule && uvicorn main:app --host 0.0.0.0 --port 8888 --reload"
    ports:
      - 5000:8888
    volumes:
      - ./src:/src